server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: moon-business-shorturl
  
  # 数据源配置
  datasource:
    url: jdbc:h2:mem:shorturl;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
        
  # Thymeleaf配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/

# 应用配置
app:
  domain: http://localhost:8080
  # 分区配置
  partition:
    enabled: true                    # 是否启用分区功能
    retention-days: 90               # 数据保留天数
    advance-days: 7                  # 提前创建分区的天数
    auto-maintenance: true           # 是否启用自动维护
    batch-size: 1000                 # 批处理大小
  
# 短链配置
shorturl:
  # 默认短链长度
  default-length: 6
  # 最大重试次数
  max-retry: 3
  # 默认过期时间（天）
  default-expire-days: 365
  # 缓存过期时间（秒）
  cache-expire-seconds: 3600
  # 机器ID（用于Snowflake算法）
  machine-id: 1

# 日志配置
logging:
  level:
    com.mooncloud.shorturl: DEBUG
    org.springframework.data.jpa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always