server:
  port: 8762

spring:
  application:
    name: eureka-client-server
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    # 作为客户端时的配置
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  server:
    # 作为服务端时的配置
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 30000
    response-cache-auto-expiration-in-seconds: 180

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix.eureka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"