version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: moon-cloud-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/var/log/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=yourpassword
    networks:
      - moon-cloud-network
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  moon-cloud-network:
    driver: bridge
    name: moon-cloud-network

volumes:
  redis-data:
    driver: local