-- Moon Business AppStore 数据库初始化脚本
-- Author: Moon Cloud
-- Date: 2024-09-26

-- 创建数据库
CREATE DATABASE IF NOT EXISTS `moon_appstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `moon_appstore`;

-- 1. 应用信息表
CREATE TABLE IF NOT EXISTS `apps` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `app_id` varchar(20) NOT NULL COMMENT 'App Store应用ID',
  `bundle_id` varchar(255) DEFAULT NULL COMMENT '应用Bundle ID',
  `name` varchar(255) NOT NULL COMMENT '应用名称',
  `subtitle` varchar(255) DEFAULT NULL COMMENT '应用副标题',
  `description` text COMMENT '应用描述',
  `developer_name` varchar(255) NOT NULL COMMENT '开发商名称',
  `developer_id` varchar(20) DEFAULT NULL COMMENT '开发商ID',
  `developer_url` varchar(500) DEFAULT NULL COMMENT '开发商网站',
  `primary_category_id` varchar(20) NOT NULL COMMENT '主分类ID',
  `primary_category_name` varchar(100) NOT NULL COMMENT '主分类名称',
  `categories` json DEFAULT NULL COMMENT '所有分类信息(JSON)',
  `version` varchar(50) DEFAULT NULL COMMENT '当前版本号',
  `release_date` datetime DEFAULT NULL COMMENT '首次发布时间',
  `updated_date` datetime DEFAULT NULL COMMENT '最后更新时间',
  `release_notes` text COMMENT '版本更新说明',
  `file_size` bigint DEFAULT NULL COMMENT '应用大小(字节)',
  `minimum_os_version` varchar(20) DEFAULT NULL COMMENT '最低系统要求',
  `icon_url` varchar(500) DEFAULT NULL COMMENT '应用图标URL',
  `screenshots` json DEFAULT NULL COMMENT '截图URLs(JSON数组)',
  `ipad_screenshots` json DEFAULT NULL COMMENT 'iPad截图URLs(JSON数组)',
  `preview_video_url` varchar(500) DEFAULT NULL COMMENT '预览视频URL',
  `rating` decimal(3,2) DEFAULT NULL COMMENT '平均评分',
  `rating_count` int DEFAULT NULL COMMENT '评分总数',
  `current_version_rating` decimal(3,2) DEFAULT NULL COMMENT '当前版本评分',
  `current_version_rating_count` int DEFAULT NULL COMMENT '当前版本评分数',
  `current_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '当前价格',
  `original_price` decimal(10,2) DEFAULT NULL COMMENT '原价(用于计算优惠)',
  `currency` varchar(10) DEFAULT 'CNY' COMMENT '货币类型',
  `is_free` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否免费应用',
  `content_rating` varchar(20) DEFAULT NULL COMMENT '内容分级',
  `languages` json DEFAULT NULL COMMENT '支持语言(JSON数组)',
  `supported_devices` json DEFAULT NULL COMMENT '支持设备(JSON数组)',
  `features` json DEFAULT NULL COMMENT '应用特性(JSON数组)',
  `has_in_app_purchase` tinyint(1) DEFAULT '0' COMMENT '是否有内购',
  `has_ads` tinyint(1) DEFAULT NULL COMMENT '是否含广告',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态: 1=正常, 0=下架',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `last_crawled_at` timestamp DEFAULT NULL COMMENT '最后爬取时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_id` (`app_id`),
  KEY `idx_category_price` (`primary_category_id`, `current_price`),
  KEY `idx_developer` (`developer_id`),
  KEY `idx_rating` (`rating`),
  KEY `idx_updated` (`updated_at`),
  KEY `idx_status_category` (`status`, `primary_category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='应用信息表';

-- 2. 限免推广记录表
CREATE TABLE IF NOT EXISTS `free_promotions` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `app_id` varchar(32) NOT NULL COMMENT '应用ID(关联apps表)',
  `appstore_app_id` varchar(20) NOT NULL COMMENT 'App Store应用ID',
  `promotion_type` varchar(20) NOT NULL DEFAULT 'FREE' COMMENT '推广类型: FREE=限免, DISCOUNT=打折',
  `original_price` decimal(10,2) NOT NULL COMMENT '原价',
  `promotion_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '推广价格',
  `discount_rate` decimal(5,2) DEFAULT NULL COMMENT '折扣率(%)',
  `savings_amount` decimal(10,2) NOT NULL COMMENT '节省金额',
  `start_time` datetime NOT NULL COMMENT '限免开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '限免结束时间(预估)',
  `actual_end_time` datetime DEFAULT NULL COMMENT '实际结束时间',
  `duration_hours` int DEFAULT NULL COMMENT '限免持续时长(小时)',
  `discovered_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '发现时间',
  `discovery_source` varchar(50) DEFAULT NULL COMMENT '发现来源: AUTO=自动, USER=用户提交, EDITOR=编辑添加',
  `confirmed_at` timestamp DEFAULT NULL COMMENT '确认时间',
  `confirmed_by` varchar(100) DEFAULT NULL COMMENT '确认人员',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE=进行中, ENDED=已结束, INVALID=无效',
  `is_featured` tinyint(1) DEFAULT '0' COMMENT '是否编辑推荐',
  `is_hot` tinyint(1) DEFAULT '0' COMMENT '是否热门',
  `priority_score` int DEFAULT '0' COMMENT '优先级得分(用于排序)',
  `view_count` int DEFAULT '0' COMMENT '查看次数',
  `click_count` int DEFAULT '0' COMMENT '点击次数',
  `share_count` int DEFAULT '0' COMMENT '分享次数',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_promotion` (`appstore_app_id`, `start_time`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_status_start` (`status`, `start_time` DESC),
  KEY `idx_featured_hot` (`is_featured`, `is_hot`, `priority_score` DESC),
  KEY `idx_discovery` (`discovered_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='限免推广记录表';

-- 3. 应用分类表
CREATE TABLE IF NOT EXISTS `categories` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `category_id` varchar(20) NOT NULL COMMENT 'App Store分类ID',
  `parent_id` varchar(20) DEFAULT NULL COMMENT '父分类ID',
  `name_cn` varchar(100) NOT NULL COMMENT '中文名称',
  `name_en` varchar(100) NOT NULL COMMENT '英文名称',
  `category_type` varchar(20) NOT NULL COMMENT '分类类型: GAME=游戏, APP=应用',
  `icon_url` varchar(500) DEFAULT NULL COMMENT '分类图标URL',
  `sort_order` int DEFAULT '0' COMMENT '排序权重',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `description` text COMMENT '分类描述',
  `app_count` int DEFAULT '0' COMMENT '应用总数',
  `free_app_count` int DEFAULT '0' COMMENT '当前限免应用数',
  `avg_rating` decimal(3,2) DEFAULT NULL COMMENT '平均评分',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_id` (`category_id`),
  KEY `idx_parent` (`parent_id`),
  KEY `idx_type_order` (`category_type`, `sort_order`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='应用分类表';

-- 4. 价格历史表
CREATE TABLE IF NOT EXISTS `price_history` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `app_id` varchar(32) NOT NULL COMMENT '应用ID(关联apps表)',
  `appstore_app_id` varchar(20) NOT NULL COMMENT 'App Store应用ID',
  `price` decimal(10,2) NOT NULL COMMENT '价格',
  `currency` varchar(10) DEFAULT 'CNY' COMMENT '货币类型',
  `price_change_type` varchar(20) DEFAULT NULL COMMENT '价格变化类型: INCREASE=上涨, DECREASE=下降, FREE=限免, NORMAL=正常',
  `change_amount` decimal(10,2) DEFAULT NULL COMMENT '变化金额',
  `change_percentage` decimal(5,2) DEFAULT NULL COMMENT '变化百分比',
  `record_date` date NOT NULL COMMENT '记录日期',
  `record_time` datetime NOT NULL COMMENT '记录时间',
  `promotion_id` varchar(32) DEFAULT NULL COMMENT '关联的限免记录ID',
  `previous_price` decimal(10,2) DEFAULT NULL COMMENT '上一次价格',
  `data_source` varchar(50) DEFAULT 'AUTO' COMMENT '数据来源: AUTO=自动采集, MANUAL=手动录入',
  `crawl_session_id` varchar(32) DEFAULT NULL COMMENT '采集批次ID',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_date_time` (`appstore_app_id`, `record_date`, `record_time`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_date` (`record_date` DESC),
  KEY `idx_app_date` (`app_id`, `record_date` DESC),
  KEY `idx_promotion` (`promotion_id`),
  KEY `idx_change_type` (`price_change_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='价格历史表';

-- 5. 搜索索引表
CREATE TABLE IF NOT EXISTS `search_index` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `app_id` varchar(32) NOT NULL COMMENT '应用ID(关联apps表)',
  `appstore_app_id` varchar(20) NOT NULL COMMENT 'App Store应用ID',
  `app_name` varchar(255) NOT NULL COMMENT '应用名称',
  `app_name_pinyin` varchar(500) DEFAULT NULL COMMENT '应用名称拼音',
  `developer_name` varchar(255) NOT NULL COMMENT '开发商名称',
  `developer_name_pinyin` varchar(500) DEFAULT NULL COMMENT '开发商名称拼音',
  `keywords` text COMMENT '关键词(从描述中提取)',
  `category_names` varchar(500) COMMENT '分类名称(多个用逗号分隔)',
  `description_snippet` text COMMENT '描述摘要',
  `search_weight` int DEFAULT '1' COMMENT '搜索权重',
  `popularity_score` decimal(5,2) DEFAULT '0.00' COMMENT '热度得分',
  `quality_score` decimal(5,2) DEFAULT '0.00' COMMENT '质量得分',
  `search_count` int DEFAULT '0' COMMENT '搜索次数',
  `click_rate` decimal(5,4) DEFAULT '0.0000' COMMENT '点击率',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_id` (`app_id`),
  KEY `idx_appstore_id` (`appstore_app_id`),
  KEY `idx_search_weight` (`search_weight` DESC),
  KEY `idx_popularity` (`popularity_score` DESC),
  FULLTEXT KEY `ft_app_name` (`app_name`, `app_name_pinyin`),
  FULLTEXT KEY `ft_developer` (`developer_name`, `developer_name_pinyin`),
  FULLTEXT KEY `ft_keywords` (`keywords`),
  FULLTEXT KEY `ft_all` (`app_name`, `developer_name`, `keywords`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='搜索索引表';

-- 6. 搜索历史表
CREATE TABLE IF NOT EXISTS `search_history` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户ID(未登录用户为NULL)',
  `device_id` varchar(64) DEFAULT NULL COMMENT '设备标识符',
  `search_query` varchar(255) NOT NULL COMMENT '搜索关键词',
  `search_query_normalized` varchar(255) DEFAULT NULL COMMENT '标准化搜索词',
  `search_type` varchar(20) DEFAULT 'NORMAL' COMMENT '搜索类型: NORMAL=普通, VOICE=语音',
  `result_count` int DEFAULT '0' COMMENT '搜索结果数量',
  `clicked_app_id` varchar(32) DEFAULT NULL COMMENT '点击的应用ID',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP地址',
  `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
  `platform` varchar(50) DEFAULT NULL COMMENT '平台信息',
  `app_version` varchar(20) DEFAULT NULL COMMENT '应用版本',
  `searched_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '搜索时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_search_query` (`search_query`),
  KEY `idx_searched_at` (`searched_at` DESC),
  KEY `idx_result_count` (`result_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='搜索历史表';

-- 初始化分类数据
INSERT INTO `categories` (`id`, `category_id`, `parent_id`, `name_cn`, `name_en`, `category_type`, `sort_order`) VALUES
('cat_001', '6014', NULL, '游戏', 'Games', 'GAME', 1),
('cat_002', '6000', NULL, '商务', 'Business', 'APP', 2),
('cat_003', '6002', NULL, '工具', 'Utilities', 'APP', 3),
('cat_004', '6003', NULL, '旅行', 'Travel', 'APP', 4),
('cat_005', '6004', NULL, '体育', 'Sports', 'APP', 5),
('cat_006', '6005', NULL, '社交', 'Social Networking', 'APP', 6),
('cat_007', '6006', NULL, '参考', 'Reference', 'APP', 7),
('cat_008', '6007', NULL, '效率', 'Productivity', 'APP', 8),
('cat_009', '6008', NULL, '摄影与录像', 'Photo & Video', 'APP', 9),
('cat_010', '6009', NULL, '新闻', 'News', 'APP', 10),
('cat_011', '6010', NULL, '导航', 'Navigation', 'APP', 11),
('cat_012', '6011', NULL, '音乐', 'Music', 'APP', 12),
('cat_013', '6012', NULL, '生活', 'Lifestyle', 'APP', 13),
('cat_014', '6013', NULL, '健康健美', 'Health & Fitness', 'APP', 14),
('cat_015', '6015', NULL, '财务', 'Finance', 'APP', 15),
('cat_016', '6016', NULL, '娱乐', 'Entertainment', 'APP', 16),
('cat_017', '6017', NULL, '教育', 'Education', 'APP', 17),
('cat_018', '6018', NULL, '图书', 'Books', 'APP', 18),
('cat_019', '6020', NULL, '医疗', 'Medical', 'APP', 19),
('cat_020', '6021', NULL, '报刊杂志', 'Newsstand', 'APP', 20),
('cat_021', '6022', NULL, '美食佳饮', 'Food & Drink', 'APP', 21),
('cat_022', '6023', NULL, '天气', 'Weather', 'APP', 22),
('cat_023', '6024', NULL, '购物', 'Shopping', 'APP', 23),
('cat_024', '6026', NULL, '贴纸', 'Stickers', 'APP', 24),
('cat_025', '6027', NULL, '开发工具', 'Developer Tools', 'APP', 25),
('cat_026', '6028', NULL, '图形和设计', 'Graphics & Design', 'APP', 26);

-- 插入游戏子分类
INSERT INTO `categories` (`id`, `category_id`, `parent_id`, `name_cn`, `name_en`, `category_type`, `sort_order`) VALUES
('cat_g01', '7001', '6014', '动作游戏', 'Action', 'GAME', 1),
('cat_g02', '7002', '6014', '冒险游戏', 'Adventure', 'GAME', 2),
('cat_g03', '7003', '6014', '街机游戏', 'Arcade', 'GAME', 3),
('cat_g04', '7004', '6014', '桌面游戏', 'Board', 'GAME', 4),
('cat_g05', '7005', '6014', '卡牌游戏', 'Card', 'GAME', 5),
('cat_g06', '7006', '6014', '赌场游戏', 'Casino', 'GAME', 6),
('cat_g07', '7007', '6014', '休闲游戏', 'Casual', 'GAME', 7),
('cat_g08', '7008', '6014', '家庭游戏', 'Family', 'GAME', 8),
('cat_g09', '7009', '6014', '音乐游戏', 'Music', 'GAME', 9),
('cat_g10', '7010', '6014', '解谜游戏', 'Puzzle', 'GAME', 10),
('cat_g11', '7011', '6014', '赛车游戏', 'Racing', 'GAME', 11),
('cat_g12', '7012', '6014', '角色扮演', 'Role Playing', 'GAME', 12),
('cat_g13', '7013', '6014', '模拟游戏', 'Simulation', 'GAME', 13),
('cat_g14', '7014', '6014', '体育游戏', 'Sports', 'GAME', 14),
('cat_g15', '7015', '6014', '策略游戏', 'Strategy', 'GAME', 15),
('cat_g16', '7016', '6014', '小游戏', 'Trivia', 'GAME', 16),
('cat_g17', '7017', '6014', '文字游戏', 'Word', 'GAME', 17);