server:
  port: 8081

resilience4j:
  ratelimiter:
    instances:
      test-limiter:
        limit-for-period: 1
        limit-refresh-period: 10s
        timeout-duration: 500ms
        register-health-indicator: true
        event-consumer-buffer-size: 100

logging:
  level:
    io.github.resilience4j: DEBUG
    com.moon.cloud: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"